name: demo_upopp
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  pin_code_fields: ^8.0.1
  intl_phone_field: ^3.2.0
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.0.0
  flutter_dash: ^1.0.0
  slide_to_act: ^2.0.2
  toggle_switch:
  flutter_faq: ^1.0.1+1
  reorderable_grid_view: ^2.2.6





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  local_auth: ^2.2.0



  # Network
  dio: ^5.1.1
 # internetF_connection_checker: ^1.0.0+1
  internet_connection_checker: ^1.0.0+1

  # Storage
  get_storage: ^2.1.1

  # UI Elements
  lottie: ^2.3.1
  flutter_svg: ^2.0.4

  # Device
  package_info_plus: ^3.0.3
  connectivity_plus: ^3.0.3
  cached_network_image: ^3.2.3

  # state management
  get: ^4.6.5

  # Utils
  intl: ^0.18.0
  get_it: ^7.2.0

  # UI
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/lotties/
    - assets/icons/drawables/
    - assets/icons/svgs/
    - assets/fonts/
    - assets/assetsimages/


  fonts:
    - family: celias
      fonts:
        - asset: assets/fonts/Celias-Bold.ttf
        - asset: assets/fonts/Celias-Book.ttf
        - asset: assets/fonts/Celias-Light.ttf
        - asset: assets/fonts/Celias-Medium.ttf
        - asset: assets/fonts/Celias-Thin.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
