/// Here declare all the english translation keys and values

const Map<String, String> englishMap = {

  "email": "Email",
  "password": "Password",
  "repeatpassword": "Repeat Password",
  "rememberMe": "Remember Me",
  "forgotPasswordWithQuestionMark": "Forgot Password?",
  "login": "Log In",
  "fundConnect": "Fund Connect",
  "portfolio": "Portfolio",
  "moneyMarketFund": "Money Market Fund",
  "leithWheelerFunds": "Leith Wheeler Funds",
  "newsFeeds": "News Feeds",
  "home": "Home",
  "logout": "Log out",
  "version": "Version",
  "portfolioValue": "Portfolio Value",
  "gain": "Gain ",
  "viewAll": "View All",
  "portfolioSummary": "Portfolio Summary",
  "globalIndices": "Global Indices",
  "news": "News",
  "totalFundValue": "Total Fund Value",
  "oneYearReturn": "1 Year Return",
  "expenseRatio": "Expense Ratio",
  "totalAUM": "Total AUM",
  "topTenHoldings": "Top 10 Holdings",
  "signIn": "Sign In",
  "dontHaveAccount": "Don't have an account? ",
  "register": "Register",
  "forgotPassword": "Forgot Password",
  "submit": "Submit",
  "firstname": "First Name",
  "lastName":"Last Name",
  "iAgreeTo": "I agree to ",
  "termsAndCondition": "Terms & Conditions",
  "alreadyHaveAccount": "Already have an account? ",
  "about": "About",
  "contact": "Contact",
  "gender":"Gender",
  "male":"Male",
  "female":"Female",
  "other":"Other",
  "createacc":"Create an account",
  "agree":"By signing up you agree to our ",
  "policy":"Privacy Policy and Terms.",
  "continueguest":"Continue as Guest.",

  "confirmOtp": "Confirm OTP",
  "confirmMsg": "Confirm the OTP to your registered Number",
  "receiveCode": "Don't receive code?",
  "confirm": "Confirm",
  "resend": "Resend",
  "confirmTimerText": "Enter OTP Code (",
  "confirmTimerText1": "Sec)",

  "enterEmailAddress": "Please enter a email address",
  "enterPassword": "Please enter a password",
  "enterValidPassword": "Please enter a valid Password",
  "pleaseEnterFirstName": "Please enter a first name",
  "pleaseEnterLastName": "Please enter a last name",
  "pleaseEnterEmail": "Please enter a email",
  "passwordLength": "The password field must be at least 6 characters",
  "repeatPassword": "Please enter a repeat password",


  "emailAddress": "Email Address",
  "fieldCannotBeEmpty": "Field cannot be empty",
  "enterValid": "Enter a valid",
  "pleaseEnter": "Please Enter a",
  "pleaseEnterPwd": "Please enter a password",
  "enterValidPwd": "Please enter a valid password",
  "passwordNotMatch": "Password does not match!",


  "somethingWentWrong": "Something went wrong",


  "networkConnectionTimeout": "Network connection timeout",
  "networkSendTimeout": "Network send timeout",
  "networkReceiveTimeout": "Network receive timeout",
  "internetNotAvailable": "Internet not available",

};
